hostconfig:
  dns: 172.16.10.1
  tod: ntp.ubuntu.com # NTP Server
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "gkeonprem.local"
blocks:
  - netmask: 255.255.255.0 
    gateway: 172.16.20.1 # DFGW for nodes
    ips:
    - ip: 172.16.20.201 # Admin control plane
      hostname: user-host1 # will be trimmed to host1
    - ip: 172.16.20.202 # Admin addon1
      hostname: user-host2  # will be trimmed to host2
    - ip: 172.16.20.203 # Admin addon2
      hostname: user-host3  # will be trimmed to host3

